### ISSUE TITLE
[Bug] The experience/level requierement only appear 1

### ISSUE THREAD

**Issue by BrecanYT** [ASangarin/TechTree#14]
![image](https://user-images.githubusercontent.com/44058869/139445942-94e70374-f5d3-4114-8649-4057953733c6.png)
![image](https://user-images.githubusercontent.com/44058869/139445987-2d124118-86aa-4f41-b7d7-3bc464243550.png)

**Comment by ASangarin** [comment]
You've configured the levels wrong.

Instead of:
`- 'level{level=200,take=true}'`
Change it to:
`- 'level{levels=200,take=true}'`
