### ISSUE TITLE
[Bug] Could not pass event InventoryClickEvent to TechTree v1.4.4.2 

### ISSUE THREAD

**Issue by 341025245** [ASangarin/TechTree#16]
**Describe the bug**
Clicking GUI slots does nothing, and sends an error in console

**To Reproduce**
MythicLib Build #235
MMOcore Build #387 
MythicMobs Premium release

**Expected behavior**
Expected for it to work

**Screenshots**
![image](https://user-images.githubusercontent.com/38593200/161391866-9cf59d38-c0a6-4cdb-8294-31d1a593b0b5.png)

**Spigot Version:**
Paper 1.18.2 

**Plugin Version:**
Latest on spigot

**Additional context**
Nothing

**Comment by Mwexim** [comment]
I can confirm this, I am having the same issues.

**Comment by ASangarin** [comment]
Fixed in 1.4.4.3
