### ISSUE TITLE
Vault money requirement not working

### ISSUE THREAD

**Issue by LoJoSho** [ASangarin/TechTree#9]
**Describe the bug**
The plugin issues an internal error whenever you put money as a requirement in a techtree.

**To Reproduce**
Put money in the requirements:
`- 'money{amount=25.00,take=true}'`

so for example:
https://hastebin.com/emenoqumuk.bash

**Expected behavior**
Money is shown in the gui and is taken once the player unlocks the research

**Screenshots**
https://i.imgur.com/wnYLMT0.png
Configuration with that screenshot, with money requirement, commented out: https://hastebin.com/resarekogo.http

https://i.imgur.com/eCyKYoT.jpeg
Configuration with money requirement: https://hastebin.com/xeduqecuna.http

**(Agriculture was the one that changed)**

Internal Error Message: https://hastebin.com/kesutehabe.bash
https://i.imgur.com/lTrrRPw.png

**Spigot Version:**
Paper 1.16

**Plugin Version:**
1.0

**Additional context**
Plugin list:
Plugins (45): AnnouncerPlus, ARIA, AuctionHouse, BetterEnd, BuycraftX, ChestShop, Chunky, Citizens, CitizensText, Civs, CMI, CMIPaperLib, CoreProtect, CraftBook, CrazyCrates, DeluxeMenus, DriveBackupV2*, DualWield*, EcoEnchants, GlassDropper, GlowAPI*, InfiniteScoreboard, JakesRTP, LiteBans, LuckPerms, mcMMO, Minepacks, MMOItems, MMOLib, Multiverse-Core, PacketListenerApi*, PinataParty, PlaceholderAPI, Plan, ProtocolLib, ServerListPlus, TAB, TechTree, TradeUI, Vault, Votifier, WorldBorder, WorldEdit, WorldGuard, XPBoost

**Comment by ASangarin** [comment]
Fixed latest build
